-- 0009_reference_data_from_filter_files.sql
-- Loads the 4 filter/reference files Master O supplied on 2026-04-24:
--   - Top 100 Commercial Carriers (parent + children) → carriers
--   - Top Clusters (105) → affiliations (type=cluster)
--   - Insurance Journal Top 100 P/C Agencies (2025) → top_agency_lists + top_agency_members (100)
--   - Top Regional Retailers (101 across 8 regions) → top_agency_lists + top_agency_members
-- Ignored: Wholesalers_MGA.xlsx (uploaded by mistake).

-- Extend top_agency_members with a region column so the Regional Retailers list
-- can group members by geography (Top 100 list leaves it NULL).
ALTER TABLE public.top_agency_members
  ADD COLUMN IF NOT EXISTS region text;

-- ============ CARRIERS (Top 100 parent groups + 301 children) ============
-- For each parent, insert a row with name=parent, group_name=parent (so it shows up
-- in its own group). Then insert each child with group_name = parent.
INSERT INTO public.carriers (name, group_name, active) VALUES
  ('State Farm Group', 'State Farm Group', true),
  ('State Farm Mutual Automobile Insurance Company', 'State Farm Group', true),
  ('State Farm Fire and Casualty Company', 'State Farm Group', true),
  ('State Farm General Insurance Company', 'State Farm Group', true),
  ('State Farm County Mutual Insurance Company of Texas', 'State Farm Group', true),
  ('State Farm Florida Insurance Company', 'State Farm Group', true),
  ('State Farm Lloyds', 'State Farm Group', true),
  ('Berkshire Hathaway Insurance Group', 'Berkshire Hathaway Insurance Group', true),
  ('National Liability & Fire Insurance Company', 'Berkshire Hathaway Insurance Group', true),
  ('National Indemnity Company', 'Berkshire Hathaway Insurance Group', true),
  ('GEICO Corp.', 'Berkshire Hathaway Insurance Group', true),
  ('Government Employees Insurance Company', 'Berkshire Hathaway Insurance Group', true),
  ('GEICO Indemnity Company', 'Berkshire Hathaway Insurance Group', true),
  ('GEICO General Insurance Company', 'Berkshire Hathaway Insurance Group', true),
  ('GEICO Casualty Company', 'Berkshire Hathaway Insurance Group', true),
  ('Guard Insurance Group', 'Berkshire Hathaway Insurance Group', true),
  ('Berkshire Hathaway Homestate Companies', 'Berkshire Hathaway Insurance Group', true),
  ('Medical Protective', 'Berkshire Hathaway Insurance Group', true),
  ('Princeton Insurance', 'Berkshire Hathaway Insurance Group', true),
  ('biBERK Insurance Services', 'Berkshire Hathaway Insurance Group', true),
  ('Progressive Insurance Group', 'Progressive Insurance Group', true),
  ('Progressive Casualty Insurance Company', 'Progressive Insurance Group', true),
  ('Progressive Direct Insurance Company', 'Progressive Insurance Group', true),
  ('Progressive Specialty Insurance Company', 'Progressive Insurance Group', true),
  ('Progressive County Mutual Insurance Company', 'Progressive Insurance Group', true),
  ('Progressive American Insurance Company', 'Progressive Insurance Group', true),
  ('Progressive Northern Insurance Company', 'Progressive Insurance Group', true),
  ('Progressive Northwestern Insurance Company', 'Progressive Insurance Group', true),
  ('Allstate Insurance Group', 'Allstate Insurance Group', true),
  ('Allstate Insurance Company', 'Allstate Insurance Group', true),
  ('Allstate Property and Casualty Insurance Company', 'Allstate Insurance Group', true),
  ('Allstate Fire and Casualty Insurance Company', 'Allstate Insurance Group', true),
  ('Esurance Insurance Company', 'Allstate Insurance Group', true),
  ('Encompass Insurance Company', 'Allstate Insurance Group', true),
  ('National General Insurance Company', 'Allstate Insurance Group', true),
  ('Liberty Mutual Holding Company', 'Liberty Mutual Holding Company', true),
  ('Liberty Mutual Insurance Company', 'Liberty Mutual Holding Company', true),
  ('Safeco Insurance Company of America', 'Liberty Mutual Holding Company', true),
  ('Ohio Casualty Insurance Company', 'Liberty Mutual Holding Company', true),
  ('Employers Insurance Company of Wausau', 'Liberty Mutual Holding Company', true),
  ('State Auto Property and Casualty Insurance Company', 'Liberty Mutual Holding Company', true),
  ('Ironshore Insurance companies', 'Liberty Mutual Holding Company', true),
  ('Travelers Group', 'Travelers Group', true),
  ('The Travelers Indemnity Company', 'Travelers Group', true),
  ('Travelers Property Casualty Company of America', 'Travelers Group', true),
  ('Travelers Casualty and Surety Company of America', 'Travelers Group', true),
  ('Standard Fire Insurance Company', 'Travelers Group', true),
  ('St. Paul Fire and Marine Insurance Company', 'Travelers Group', true),
  ('USAA Group', 'USAA Group', true),
  ('United Services Automobile Association', 'USAA Group', true),
  ('USAA Casualty Insurance Company', 'USAA Group', true),
  ('USAA General Indemnity Company', 'USAA Group', true),
  ('Garrison Property and Casualty Insurance Company', 'USAA Group', true),
  ('Chubb INA Group', 'Chubb INA Group', true),
  ('Federal Insurance Company', 'Chubb INA Group', true),
  ('Pacific Indemnity Company', 'Chubb INA Group', true),
  ('Great Northern Insurance Company', 'Chubb INA Group', true),
  ('ACE American Insurance Company', 'Chubb INA Group', true),
  ('ACE Property and Casualty Insurance Company', 'Chubb INA Group', true),
  ('Westchester Fire Insurance Company', 'Chubb INA Group', true),
  ('Indemnity Insurance Company of North America', 'Chubb INA Group', true),
  ('Nationwide Group', 'Nationwide Group', true),
  ('Nationwide Mutual Insurance Company', 'Nationwide Group', true),
  ('Nationwide Agribusiness Insurance Company', 'Nationwide Group', true),
  ('Nationwide Property and Casualty Insurance Company', 'Nationwide Group', true),
  ('Scottsdale Insurance Company', 'Nationwide Group', true),
  ('Farmland Mutual Insurance Company', 'Nationwide Group', true),
  ('Farmers Insurance Group', 'Farmers Insurance Group', true),
  ('Farmers Insurance Exchange', 'Farmers Insurance Group', true),
  ('Fire Insurance Exchange', 'Farmers Insurance Group', true),
  ('Truck Insurance Exchange', 'Farmers Insurance Group', true),
  ('Mid-Century Insurance Company', 'Farmers Insurance Group', true),
  ('Bristol West Insurance Company', 'Farmers Insurance Group', true),
  ('Foremost Insurance Company Grand Rapids Michigan', 'Farmers Insurance Group', true),
  ('American Family Insurance Group', 'American Family Insurance Group', true),
  ('American Family Mutual Insurance Company SI', 'American Family Insurance Group', true),
  ('Midvale Indemnity Company', 'American Family Insurance Group', true),
  ('Homesite Insurance Company', 'American Family Insurance Group', true),
  ('The General Automobile Insurance Services, Inc.', 'American Family Insurance Group', true),
  ('Ameriprise Auto & Home Insurance companies', 'American Family Insurance Group', true),
  ('The Hartford Insurance Group', 'The Hartford Insurance Group', true),
  ('Hartford Fire Insurance Company', 'The Hartford Insurance Group', true),
  ('Hartford Casualty Insurance Company', 'The Hartford Insurance Group', true),
  ('Sentinel Insurance Company', 'The Hartford Insurance Group', true),
  ('Twin City Fire Insurance Company', 'The Hartford Insurance Group', true),
  ('Hartford Underwriters Insurance Company', 'The Hartford Insurance Group', true),
  ('American International Group (AIG)', 'American International Group (AIG)', true),
  ('National Union Fire Insurance Company of Pittsburgh, Pa.', 'American International Group (AIG)', true),
  ('Lexington Insurance Company', 'American International Group (AIG)', true),
  ('American Home Assurance Company', 'American International Group (AIG)', true),
  ('New Hampshire Insurance Company', 'American International Group (AIG)', true),
  ('Illinois National Insurance Company', 'American International Group (AIG)', true),
  ('Validus specialty companies', 'American International Group (AIG)', true),
  ('Fairfax Financial (USA) Group', 'Fairfax Financial (USA) Group', true),
  ('Crum & Forster Insurance Companies', 'Fairfax Financial (USA) Group', true),
  ('Zenith Insurance Company', 'Fairfax Financial (USA) Group', true),
  ('Allied World National Assurance Company', 'Fairfax Financial (USA) Group', true),
  ('Northbridge US companies', 'Fairfax Financial (USA) Group', true),
  ('OdysseyRe US companies', 'Fairfax Financial (USA) Group', true),
  ('Auto-Owners Insurance Group', 'Auto-Owners Insurance Group', true),
  ('Auto-Owners Insurance Company', 'Auto-Owners Insurance Group', true),
  ('Owners Insurance Company', 'Auto-Owners Insurance Group', true),
  ('Home-Owners Insurance Company', 'Auto-Owners Insurance Group', true),
  ('Property-Owners Insurance Company', 'Auto-Owners Insurance Group', true),
  ('Tokio Marine US P&C Group', 'Tokio Marine US P&C Group', true),
  ('Philadelphia Indemnity Insurance Company', 'Tokio Marine US P&C Group', true),
  ('Tokio Marine America Insurance Company', 'Tokio Marine US P&C Group', true),
  ('First Insurance Company of Hawaii', 'Tokio Marine US P&C Group', true),
  ('Delphi Financial workers comp companies', 'Tokio Marine US P&C Group', true),
  ('Erie Insurance Group', 'Erie Insurance Group', true),
  ('Erie Insurance Exchange', 'Erie Insurance Group', true),
  ('Erie Insurance Company', 'Erie Insurance Group', true),
  ('Erie Insurance Company of New York', 'Erie Insurance Group', true),
  ('W. R. Berkley Insurance Group', 'W. R. Berkley Insurance Group', true),
  ('Berkley Insurance Company', 'W. R. Berkley Insurance Group', true),
  ('Berkley Regional Insurance Company', 'W. R. Berkley Insurance Group', true),
  ('Berkley National Insurance Company', 'W. R. Berkley Insurance Group', true),
  ('Acadia Insurance Company', 'W. R. Berkley Insurance Group', true),
  ('Carolina Casualty Insurance Company', 'W. R. Berkley Insurance Group', true),
  ('Continental Western Insurance Company', 'W. R. Berkley Insurance Group', true),
  ('Nautilus Insurance Company', 'W. R. Berkley Insurance Group', true),
  ('Preferred Employers Insurance Company', 'W. R. Berkley Insurance Group', true),
  ('Gemini Insurance Company', 'W. R. Berkley Insurance Group', true),
  ('Everest Re Group', 'Everest Re Group', true),
  ('Everest Indemnity Insurance Company', 'Everest Re Group', true),
  ('Everest National Insurance Company', 'Everest Re Group', true),
  ('Everest Reinsurance Company', 'Everest Re Group', true),
  ('Munich-American Holding Corp.', 'Munich-American Holding Corp.', true),
  ('American Modern Insurance Group', 'Munich-American Holding Corp.', true),
  ('Hartford Steam Boiler Inspection and Insurance Company', 'Munich-American Holding Corp.', true),
  ('Munich Reinsurance America, Inc.', 'Munich-American Holding Corp.', true),
  ('Midland Company', 'Munich-American Holding Corp.', true),
  ('Roanoke Insurance Group', 'Munich-American Holding Corp.', true),
  ('Cincinnati Insurance Companies', 'Cincinnati Insurance Companies', true),
  ('The Cincinnati Insurance Company', 'Cincinnati Insurance Companies', true),
  ('The Cincinnati Indemnity Company', 'Cincinnati Insurance Companies', true),
  ('The Cincinnati Casualty Company', 'Cincinnati Insurance Companies', true),
  ('Auto Club Enterprises Insurance Group', 'Auto Club Enterprises Insurance Group', true),
  ('Interinsurance Exchange of the Automobile Club', 'Auto Club Enterprises Insurance Group', true),
  ('Auto Club Insurance Company of Florida', 'Auto Club Enterprises Insurance Group', true),
  ('MemberSelect Insurance Company', 'Auto Club Enterprises Insurance Group', true),
  ('CSAA Insurance Group', 'CSAA Insurance Group', true),
  ('CSAA Insurance Exchange', 'CSAA Insurance Group', true),
  ('CSAA General Insurance Company', 'CSAA Insurance Group', true),
  ('CSAA Fire & Casualty Insurance Company', 'CSAA Insurance Group', true),
  ('Great American P&C Insurance Group', 'Great American P&C Insurance Group', true),
  ('Great American Insurance Company', 'Great American P&C Insurance Group', true),
  ('Great American Assurance Company', 'Great American P&C Insurance Group', true),
  ('Mid-Continent Casualty Company', 'Great American P&C Insurance Group', true),
  ('National Interstate Insurance Company', 'Great American P&C Insurance Group', true),
  ('Arch Insurance Group', 'Arch Insurance Group', true),
  ('Arch Insurance Company', 'Arch Insurance Group', true),
  ('Arch Specialty Insurance Company', 'Arch Insurance Group', true),
  ('Arch Indemnity Insurance Company', 'Arch Insurance Group', true),
  ('Arch Reinsurance Company', 'Arch Insurance Group', true),
  ('FM Group', 'FM Group', true),
  ('Factory Mutual Insurance Company', 'FM Group', true),
  ('Affiliated FM Insurance Company', 'FM Group', true),
  ('Markel Insurance Group', 'Markel Insurance Group', true),
  ('Markel American Insurance Company', 'Markel Insurance Group', true),
  ('Markel Insurance Company', 'Markel Insurance Group', true),
  ('Markel Global Reinsurance Company', 'Markel Insurance Group', true),
  ('State National Insurance Company', 'Markel Insurance Group', true),
  ('Hanover Insurance Group', 'Hanover Insurance Group', true),
  ('The Hanover Insurance Company', 'Hanover Insurance Group', true),
  ('Hanover American Insurance Company', 'Hanover Insurance Group', true),
  ('Citizens Insurance Company of America', 'Hanover Insurance Group', true),
  ('Massachusetts Bay Insurance Company', 'Hanover Insurance Group', true),
  ('Zurich Insurance US P&C Group', 'Zurich Insurance US P&C Group', true),
  ('Zurich American Insurance Company', 'Zurich Insurance US P&C Group', true),
  ('American Guarantee and Liability Insurance Company', 'Zurich Insurance US P&C Group', true),
  ('Steadfast Insurance Company', 'Zurich Insurance US P&C Group', true),
  ('Empire Fire and Marine Insurance Company', 'Zurich Insurance US P&C Group', true),
  ('Universal Underwriters Insurance Company', 'Zurich Insurance US P&C Group', true),
  ('Mercury Casualty Group', 'Mercury Casualty Group', true),
  ('Mercury Insurance Company', 'Mercury Casualty Group', true),
  ('Mercury Casualty Company', 'Mercury Casualty Group', true),
  ('California Automobile Insurance Company', 'Mercury Casualty Group', true),
  ('Selective Insurance Group', 'Selective Insurance Group', true),
  ('Selective Insurance Company of America', 'Selective Insurance Group', true),
  ('Selective Way Insurance Company', 'Selective Insurance Group', true),
  ('Selective Insurance Company of South Carolina', 'Selective Insurance Group', true),
  ('Allianz US P&C Insurance Companies', 'Allianz US P&C Insurance Companies', true),
  ('Allianz Global Risks US Insurance Company', 'Allianz US P&C Insurance Companies', true),
  ('Fireman’s Fund Insurance Company', 'Allianz US P&C Insurance Companies', true),
  ('National Surety Corporation', 'Allianz US P&C Insurance Companies', true),
  ('Kemper P&C Companies', 'Kemper P&C Companies', true),
  ('Kemper Independence Insurance Company', 'Kemper P&C Companies', true),
  ('Infinity Insurance Company', 'Kemper P&C Companies', true),
  ('Infinity Auto Insurance Company', 'Kemper P&C Companies', true),
  ('American Access Casualty Company', 'Kemper P&C Companies', true),
  ('QBE North America Group', 'QBE North America Group', true),
  ('QBE Insurance Corporation', 'QBE North America Group', true),
  ('QBE Specialty Insurance Company', 'QBE North America Group', true),
  ('General Casualty Company of Wisconsin', 'QBE North America Group', true),
  ('Sentry Insurance Group', 'Sentry Insurance Group', true),
  ('Sentry Insurance a Mutual Company', 'Sentry Insurance Group', true),
  ('Sentry Select Insurance Company', 'Sentry Insurance Group', true),
  ('Dairyland Insurance Company', 'Sentry Insurance Group', true),
  ('Viking Insurance Company of Wisconsin', 'Sentry Insurance Group', true),
  ('Assurant P&C Group', 'Assurant P&C Group', true),
  ('American Bankers Insurance Company of Florida', 'Assurant P&C Group', true),
  ('American Security Insurance Company', 'Assurant P&C Group', true),
  ('Standard Guaranty Insurance Company', 'Assurant P&C Group', true),
  ('Citizens Property Insurance Corporation', 'Citizens Property Insurance Corporation', true),
  ('Citizens Property Insurance Corporation', 'Citizens Property Insurance Corporation', true),
  ('Old Republic Insurance Group', 'Old Republic Insurance Group', true),
  ('Old Republic Insurance Company', 'Old Republic Insurance Group', true),
  ('Old Republic General Insurance Corporation', 'Old Republic Insurance Group', true),
  ('Old Republic Surety Company', 'Old Republic Insurance Group', true),
  ('BITCO General Insurance Corporation', 'Old Republic Insurance Group', true),
  ('AmTrust Group', 'AmTrust Group', true),
  ('AmTrust North America, Inc.', 'AmTrust Group', true),
  ('AmTrust Insurance Company', 'AmTrust Group', true),
  ('Wesco Insurance Company', 'AmTrust Group', true),
  ('Technology Insurance Company, Inc.', 'AmTrust Group', true),
  ('Auto Club Group', 'Auto Club Group', true),
  ('Auto Club Insurance Association', 'Auto Club Group', true),
  ('Meemic Insurance Company', 'Auto Club Group', true),
  ('COUNTRY Financial P&C Group', 'COUNTRY Financial P&C Group', true),
  ('Country Mutual Insurance Company', 'COUNTRY Financial P&C Group', true),
  ('Country Preferred Insurance Company', 'COUNTRY Financial P&C Group', true),
  ('Country Casualty Insurance Company', 'COUNTRY Financial P&C Group', true),
  ('BAMR US P&C Group', 'BAMR US P&C Group', true),
  ('The Doctors Company', 'BAMR US P&C Group', true),
  ('Medical Professional Mutual Insurance Company', 'BAMR US P&C Group', true),
  ('ProAssurance companies', 'BAMR US P&C Group', true),
  ('Starr International Group', 'Starr International Group', true),
  ('Starr Indemnity & Liability Company', 'Starr International Group', true),
  ('Starr Surplus Lines Insurance Company', 'Starr International Group', true),
  ('Starr Specialty Insurance Company', 'Starr International Group', true),
  ('Westfield Group', 'Westfield Group', true),
  ('Westfield Insurance Company', 'Westfield Group', true),
  ('Westfield National Insurance Company', 'Westfield Group', true),
  ('Ohio Farmers Insurance Company', 'Westfield Group', true),
  ('Federated Mutual Group', 'Federated Mutual Group', true),
  ('Federated Mutual Insurance Company', 'Federated Mutual Group', true),
  ('Federated Service Insurance Company', 'Federated Mutual Group', true),
  ('Federated Reserve Insurance Company', 'Federated Mutual Group', true),
  ('NJM Insurance Group', 'NJM Insurance Group', true),
  ('New Jersey Manufacturers Insurance Company', 'NJM Insurance Group', true),
  ('NJM Property-Casualty Insurance Company', 'NJM Insurance Group', true),
  ('AF Group', 'AF Group', true),
  ('Accident Fund Insurance Company of America', 'AF Group', true),
  ('United Wisconsin Insurance Company', 'AF Group', true),
  ('CompWest Insurance Company', 'AF Group', true),
  ('Farm Bureau P&C Group', 'Farm Bureau P&C Group', true),
  ('Farm Bureau Mutual Insurance Company affiliates across multiple states', 'Farm Bureau P&C Group', true),
  ('Alfa Insurance Group', 'Alfa Insurance Group', true),
  ('Alfa Insurance Corporation', 'Alfa Insurance Group', true),
  ('Alfa Mutual Insurance Company', 'Alfa Insurance Group', true),
  ('Alfa Specialty Insurance Corporation', 'Alfa Insurance Group', true),
  ('Southern Farm Bureau Casualty Group', 'Southern Farm Bureau Casualty Group', true),
  ('Southern Farm Bureau Casualty Insurance Company', 'Southern Farm Bureau Casualty Group', true),
  ('Southern Farm Bureau Life affiliates where applicable', 'Southern Farm Bureau Casualty Group', true),
  ('West Bend Insurance Group', 'West Bend Insurance Group', true),
  ('West Bend Mutual Insurance Company', 'West Bend Insurance Group', true),
  ('Tennessee Farmers Group', 'Tennessee Farmers Group', true),
  ('Tennessee Farmers Mutual Insurance Company', 'Tennessee Farmers Group', true),
  ('Texas Farm Bureau Insurance Group', 'Texas Farm Bureau Insurance Group', true),
  ('Texas Farm Bureau Mutual Insurance Company', 'Texas Farm Bureau Insurance Group', true),
  ('Southern Farm Bureau Casualty affiliates in Texas operations', 'Texas Farm Bureau Insurance Group', true),
  ('EMC Insurance Companies', 'EMC Insurance Companies', true),
  ('Employers Mutual Casualty Company', 'EMC Insurance Companies', true),
  ('EMCASCO Insurance Company', 'EMC Insurance Companies', true),
  ('Union Insurance Company', 'EMC Insurance Companies', true),
  ('MAPFRE North America Group', 'MAPFRE North America Group', true),
  ('MAPFRE Insurance Company', 'MAPFRE North America Group', true),
  ('Commerce Insurance Company', 'MAPFRE North America Group', true),
  ('Citation Insurance Company', 'MAPFRE North America Group', true),
  ('RLI Insurance Group', 'RLI Insurance Group', true),
  ('RLI Insurance Company', 'RLI Insurance Group', true),
  ('Mt. Hawley Insurance Company', 'RLI Insurance Group', true),
  ('Philadelphia Contributionship Group', 'Philadelphia Contributionship Group', true),
  ('The Philadelphia Contributionship', 'Philadelphia Contributionship Group', true),
  ('Brotherhood Mutual Group', 'Brotherhood Mutual Group', true),
  ('Brotherhood Mutual Insurance Company', 'Brotherhood Mutual Group', true),
  ('State Auto Group', 'State Auto Group', true),
  ('State Automobile Mutual Insurance Company', 'State Auto Group', true),
  ('State Auto Property and Casualty Insurance Company', 'State Auto Group', true),
  ('Donegal Group', 'Donegal Group', true),
  ('Donegal Mutual Insurance Company', 'Donegal Group', true),
  ('Atlantic States Insurance Company', 'Donegal Group', true),
  ('Southern Insurance Company of Virginia', 'Donegal Group', true),
  ('Utica National Insurance Group', 'Utica National Insurance Group', true),
  ('Utica Mutual Insurance Company', 'Utica National Insurance Group', true),
  ('Graphic Arts Mutual Insurance Company', 'Utica National Insurance Group', true),
  ('Penn National Insurance Group', 'Penn National Insurance Group', true),
  ('Pennsylvania National Mutual Casualty Insurance Company', 'Penn National Insurance Group', true),
  ('Penn National Security Insurance Company', 'Penn National Insurance Group', true),
  ('Church Mutual Group', 'Church Mutual Group', true),
  ('Church Mutual Insurance Company, S.I.', 'Church Mutual Group', true),
  ('Pure Companies Group', 'Pure Companies Group', true),
  ('Privilege Underwriters Reciprocal Exchange (PURE)', 'Pure Companies Group', true),
  ('Pure Property and Casualty Insurance Company', 'Pure Companies Group', true),
  ('Amica Mutual Group', 'Amica Mutual Group', true),
  ('Amica Mutual Insurance Company', 'Amica Mutual Group', true),
  ('Amica Property and Casualty Insurance Company', 'Amica Mutual Group', true),
  ('American Financial Group', 'American Financial Group', true),
  ('Great American Insurance Group subsidiaries', 'American Financial Group', true),
  ('National Interstate Insurance Company', 'American Financial Group', true),
  ('Shelter Insurance Group', 'Shelter Insurance Group', true),
  ('Shelter Mutual Insurance Company', 'Shelter Insurance Group', true),
  ('Shelter General Insurance Company', 'Shelter Insurance Group', true),
  ('Motorists Mutual Group', 'Motorists Mutual Group', true),
  ('Motorists Mutual Insurance Company', 'Motorists Mutual Group', true),
  ('BrickStreet Mutual Insurance Company', 'Motorists Mutual Group', true),
  ('Grange Insurance Group', 'Grange Insurance Group', true),
  ('Grange Mutual Casualty Company', 'Grange Insurance Group', true),
  ('Grange Insurance Company', 'Grange Insurance Group', true),
  ('Integrity Insurance Company', 'Grange Insurance Group', true),
  ('The Doctors Company Group', 'The Doctors Company Group', true),
  ('The Doctors Company', 'The Doctors Company Group', true),
  ('TDC Specialty Insurance Company', 'The Doctors Company Group', true),
  ('ProAssurance Group', 'ProAssurance Group', true),
  ('ProAssurance Indemnity Company', 'ProAssurance Group', true),
  ('Medmarc Casualty Insurance Company', 'ProAssurance Group', true),
  ('Ascot Group US', 'Ascot Group US', true),
  ('Ascot Insurance Company', 'Ascot Group US', true),
  ('Ascot Specialty Insurance Company', 'Ascot Group US', true),
  ('Canopius US Group', 'Canopius US Group', true),
  ('Canopius US Insurance, Inc.', 'Canopius US Group', true),
  ('Canopius Underwriting Agency US operations', 'Canopius US Group', true),
  ('Sompo North America Group', 'Sompo North America Group', true),
  ('Sompo America Insurance Company', 'Sompo North America Group', true),
  ('Sompo Specialty Insurance Company', 'Sompo North America Group', true),
  ('AXIS US Insurance Operations', 'AXIS US Insurance Operations', true),
  ('Axis Insurance Company', 'AXIS US Insurance Operations', true),
  ('Axis Surplus Insurance Company', 'AXIS US Insurance Operations', true),
  ('PartnerRe US Group', 'PartnerRe US Group', true),
  ('Partner Reinsurance Company of the U.S.', 'PartnerRe US Group', true),
  ('PartnerRe America Insurance Company', 'PartnerRe US Group', true),
  ('Swiss Re Corporate Solutions Group', 'Swiss Re Corporate Solutions Group', true),
  ('Westport Insurance Corporation', 'Swiss Re Corporate Solutions Group', true),
  ('Swiss Re Corporate Solutions America Insurance Corporation', 'Swiss Re Corporate Solutions Group', true),
  ('CNA Insurance Group', 'CNA Insurance Group', true),
  ('Continental Casualty Company', 'CNA Insurance Group', true),
  ('Continental Insurance Company', 'CNA Insurance Group', true),
  ('Valley Forge Insurance Company', 'CNA Insurance Group', true),
  ('Columbia Casualty Company', 'CNA Insurance Group', true),
  ('Somerset Re Group', 'Somerset Re Group', true),
  ('Various specialty P&C carriers and reinsurers in US operations', 'Somerset Re Group', true),
  ('American National P&C Group', 'American National P&C Group', true),
  ('American National Property And Casualty Company', 'American National P&C Group', true),
  ('American National General Insurance Company', 'American National P&C Group', true),
  ('National General Group', 'National General Group', true),
  ('National General Insurance Company', 'National General Group', true),
  ('Integon National Insurance Company', 'National General Group', true),
  ('Century-National Insurance Company', 'National General Group', true),
  ('Aspen US Insurance Group', 'Aspen US Insurance Group', true),
  ('Aspen American Insurance Company', 'Aspen US Insurance Group', true),
  ('Aspen Specialty Insurance Company', 'Aspen US Insurance Group', true),
  ('Homesite Group', 'Homesite Group', true),
  ('Homesite Insurance Company', 'Homesite Group', true),
  ('Homesite Insurance Company of the Midwest', 'Homesite Group', true),
  ('Homesite Insurance Company of Florida', 'Homesite Group', true),
  ('Lemonade Insurance Group', 'Lemonade Insurance Group', true),
  ('Lemonade Insurance Company', 'Lemonade Insurance Group', true),
  ('Metromile Insurance Company', 'Lemonade Insurance Group', true),
  ('Root Insurance Group', 'Root Insurance Group', true),
  ('Root Insurance Company', 'Root Insurance Group', true),
  ('Crum & Forster Group', 'Crum & Forster Group', true),
  ('Crum and Forster Insurance Company', 'Crum & Forster Group', true),
  ('North River Insurance Company', 'Crum & Forster Group', true),
  ('Seneca Insurance Company', 'Crum & Forster Group', true),
  ('Zenith Insurance Group', 'Zenith Insurance Group', true),
  ('The Zenith Insurance Company', 'Zenith Insurance Group', true),
  ('Zenith Insurance Company subsidiaries', 'Zenith Insurance Group', true),
  ('Allied World US Group', 'Allied World US Group', true),
  ('Allied World Assurance Company (U.S.) Inc.', 'Allied World US Group', true),
  ('Allied World National Assurance Company', 'Allied World US Group', true),
  ('Palomar Insurance Holdings Group', 'Palomar Insurance Holdings Group', true),
  ('Palomar Specialty Insurance Company', 'Palomar Insurance Holdings Group', true),
  ('Kinsale Insurance Group', 'Kinsale Insurance Group', true),
  ('Kinsale Insurance Company', 'Kinsale Insurance Group', true),
  ('James River Group', 'James River Group', true),
  ('James River Insurance Company', 'James River Group', true),
  ('Falls Lake National Insurance Company', 'James River Group', true),
  ('Skyward Specialty Group', 'Skyward Specialty Group', true),
  ('Houston Specialty Insurance Company', 'Skyward Specialty Group', true),
  ('Imperium Insurance Company', 'Skyward Specialty Group', true),
  ('Trisura Specialty Group', 'Trisura Specialty Group', true),
  ('Trisura Specialty Insurance Company', 'Trisura Specialty Group', true),
  ('American Coastal Insurance Group', 'American Coastal Insurance Group', true),
  ('American Coastal Insurance Company', 'American Coastal Insurance Group', true),
  ('Interboro Insurance Company', 'American Coastal Insurance Group', true),
  ('FedNat/Monarch Group', 'FedNat/Monarch Group', true),
  ('Monarch National Insurance Company', 'FedNat/Monarch Group', true),
  ('Heritage Insurance Holdings Group', 'Heritage Insurance Holdings Group', true),
  ('Heritage Property & Casualty Insurance Company', 'Heritage Insurance Holdings Group', true),
  ('Narragansett Bay Insurance Company', 'Heritage Insurance Holdings Group', true),
  ('United Heritage P&C Group', 'United Heritage P&C Group', true),
  ('United Heritage Property & Casualty Company', 'United Heritage P&C Group', true),
  ('Donegal Commercial Lines affiliates', 'Donegal Commercial Lines affiliates', true),
  ('Donegal affiliates focused on commercial lines', 'Donegal Commercial Lines affiliates', true),
  ('CopperPoint Insurance Group', 'CopperPoint Insurance Group', true),
  ('CopperPoint Insurance Company', 'CopperPoint Insurance Group', true),
  ('Pacific Compensation Insurance Company', 'CopperPoint Insurance Group', true),
  ('Employers Holdings Group', 'Employers Holdings Group', true),
  ('Employers Insurance Company of Nevada', 'Employers Holdings Group', true),
  ('Employers Compensation Insurance Company', 'Employers Holdings Group', true);

-- ============ CLUSTERS → affiliations (type='cluster') ============
INSERT INTO public.affiliations (canonical_name, type, active, sort_order) VALUES
  ('FirstChoice, a MarshBerry Company', 'cluster', true, 1),
  ('SIAA', 'cluster', true, 2),
  ('Indium', 'cluster', true, 3),
  ('Keystone Insurers Group LLC', 'cluster', true, 4),
  ('ISU Steadfast Insurance Agency Network', 'cluster', true, 5),
  ('Renaissance', 'cluster', true, 6),
  ('The Agency Collective LLC', 'cluster', true, 7),
  ('SecureRisk LLC', 'cluster', true, 8),
  ('Ironpeak', 'cluster', true, 9),
  ('Fortified', 'cluster', true, 10),
  ('Combined Agents of America', 'cluster', true, 11),
  ('Smart Choice', 'cluster', true, 12),
  ('Pacific Interstate Insurance Brokers', 'cluster', true, 13),
  ('GreatFlorida Insurance', 'cluster', true, 14),
  ('Fiesta Insurance Franchise Corp. dba Fiesta Auto Insurance Center', 'cluster', true, 15),
  ('Insurors Group LLC', 'cluster', true, 16),
  ('Agents Alliance Services LLC', 'cluster', true, 17),
  ('United Agencies', 'cluster', true, 18),
  ('We Insure', 'cluster', true, 19),
  ('SBMP Insurance Group', 'cluster', true, 20),
  ('Combined Agents of America LLC', 'cluster', true, 21),
  ('Smart Choice Agents', 'cluster', true, 22),
  ('Brightway Insurance', 'cluster', true, 23),
  ('Fiesta Insurance Franchise Corp (Fiesta Auto Insurance Centers)', 'cluster', true, 24),
  ('Insurance Associates of America', 'cluster', true, 25),
  ('United Agencies, Inc.', 'cluster', true, 26),
  ('PacWest Alliance Insurance Services Inc.', 'cluster', true, 27),
  ('Amwins Direct Access Insurance Services (DAIS)', 'cluster', true, 28),
  ('Strategic Agency Partners', 'cluster', true, 29),
  ('Atlas Insurance Brokers', 'cluster', true, 30),
  ('Agency Network Exchange (ANE)', 'cluster', true, 31),
  ('Mountain Empire Agency Alliance (MEAA)', 'cluster', true, 32),
  ('The Iroquois Group', 'cluster', true, 33),
  ('GreatFlorida Insurance (network)', 'cluster', true, 34),
  ('ISU Insurance Agency Network', 'cluster', true, 35),
  ('TWFG Insurance Services', 'cluster', true, 36),
  ('TWG Insurance', 'cluster', true, 37),
  ('TWG General Agency', 'cluster', true, 38),
  ('Main Street America Group (aggregator programs)', 'cluster', true, 39),
  ('ISG United', 'cluster', true, 40),
  ('Agents Alliance', 'cluster', true, 41),
  ('Blue Ridge Insurance Partners', 'cluster', true, 42),
  ('Capital Area Independent Agents', 'cluster', true, 43),
  ('Austin Association of Insurance Agents', 'cluster', true, 44),
  ('Alliance Insurance Services', 'cluster', true, 45),
  ('Alliance Insurance Group of Kansas', 'cluster', true, 46),
  ('American West Insurance Agency Alliance', 'cluster', true, 47),
  ('Associated Insurance Services', 'cluster', true, 48),
  ('Coast General Insurance Brokers Network', 'cluster', true, 49),
  ('Renaissance Alliance', 'cluster', true, 50),
  ('Pacific Interstate Insurance Brokers (PIIB)', 'cluster', true, 51),
  ('SecureRisk', 'cluster', true, 52),
  ('Ironpeak Alliance', 'cluster', true, 53),
  ('Fortified Insurance Group', 'cluster', true, 54),
  ('GreatFlorida Insurance Franchise Network', 'cluster', true, 55),
  ('Brightway Insurance Franchise Network', 'cluster', true, 56),
  ('Fiesta Auto Insurance Centers', 'cluster', true, 57),
  ('Keystone Insurers Group', 'cluster', true, 58),
  ('ISU Network', 'cluster', true, 59),
  ('The Agency Collective', 'cluster', true, 60),
  ('FirstChoice Growth Solutions', 'cluster', true, 61),
  ('SIAA Agency Alliance', 'cluster', true, 62),
  ('Indium Insurance Services', 'cluster', true, 63),
  ('PacWest Alliance Insurance Services', 'cluster', true, 64),
  ('Insurors Group', 'cluster', true, 65),
  ('Insurance Associates of America Network', 'cluster', true, 66),
  ('United Agencies Network', 'cluster', true, 67),
  ('Amwins DAIS', 'cluster', true, 68),
  ('Strategic Agency Partners Network', 'cluster', true, 69),
  ('Atlas Insurance Brokers Network', 'cluster', true, 70),
  ('Agency Network Exchange', 'cluster', true, 71),
  ('Mountain Empire Agency Alliance', 'cluster', true, 72),
  ('ISG United Insurance Network', 'cluster', true, 73),
  ('Agents Alliance Network', 'cluster', true, 74),
  ('Blue Ridge Insurance Partners Network', 'cluster', true, 75),
  ('Capital Area Independent Agents Association', 'cluster', true, 76),
  ('Austin Association of Insurance Agents Network', 'cluster', true, 77),
  ('Alliance Insurance Services Network', 'cluster', true, 78),
  ('Alliance Insurance Group of Kansas Network', 'cluster', true, 79),
  ('American West Insurance Agency Alliance Network', 'cluster', true, 80),
  ('Associated Insurance Services Network', 'cluster', true, 81),
  ('Coast General Insurance Brokers Alliance', 'cluster', true, 82),
  ('ISU Steadfast', 'cluster', true, 83),
  ('FirstChoice (MarshBerry)', 'cluster', true, 84),
  ('Smart Choice Agents Program', 'cluster', true, 85),
  ('Renaissance Alliance Insurance Services', 'cluster', true, 86),
  ('Keystone Insurers Group Inc.', 'cluster', true, 87),
  ('Fiesta Insurance Franchise Corp', 'cluster', true, 88),
  ('GreatFlorida Insurance Network', 'cluster', true, 89),
  ('Brightway Insurance Network', 'cluster', true, 90),
  ('SecureRisk Insurance Network', 'cluster', true, 91),
  ('Pacific Interstate Insurance Brokers Network', 'cluster', true, 92),
  ('The Iroquois Group Network', 'cluster', true, 93),
  ('ISU Steadfast Insurance Agency Network LLC', 'cluster', true, 94),
  ('FirstChoice Agency Network', 'cluster', true, 95),
  ('SIAA Strategic Insurance Agency Alliance', 'cluster', true, 96),
  ('Indium Agency Network', 'cluster', true, 97),
  ('Combined Agents of America Network', 'cluster', true, 98),
  ('Atlas Insurance Brokers Cluster', 'cluster', true, 99),
  ('Amwins Direct Access Insurance Services Network', 'cluster', true, 100),
  ('ISG United Agency Network', 'cluster', true, 101),
  ('Agency Network Exchange LLC', 'cluster', true, 102),
  ('Mountain Empire Agency Alliance LLC', 'cluster', true, 103),
  ('PacWest Alliance Insurance Services Network', 'cluster', true, 104),
  ('SBMP Insurance Group Network', 'cluster', true, 105);

-- ============ TOP AGENCY LISTS + MEMBERS ============
-- Create both lists first (with deterministic UUIDs so we can reference them).
-- List A: Insurance Journal Top 100 (2025)
-- List B: Top Regional Retailers
WITH list_a AS (
  INSERT INTO public.top_agency_lists (name, year, description)
  VALUES (
    'Insurance Journal Top 100 Property/Casualty Agencies (2025)',
    2025,
    '21st annual ranking of independent P/C agencies by Insurance Journal. Ranked by P/C revenue.'
  )
  RETURNING id
),
list_b AS (
  INSERT INTO public.top_agency_lists (name, year, description)
  VALUES (
    'Top Regional Retailers by Geography',
    NULL,
    'Regional commercial P/C retail agencies grouped by US geographic region. Not rank-ordered.'
  )
  RETURNING id
),
members_a AS (
  INSERT INTO public.top_agency_members (top_agency_list_id, rank, agency_name, pc_revenue, other_revenue, office_city, office_state)
  SELECT (SELECT id FROM list_a), u.rank, u.name, u.pc, u.other, u.city, u.state
  FROM UNNEST(
    ARRAY[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100]::int[],
    ARRAY['Alliant Insurance Services/Confie','HUB International Ltd.','Acrisure LLC','Lockton','AssuredPartners','BroadStreet Partners Inc.','USI Insurance Services','Accession Risk Management Group','The Baldwin Group','EPIC Insurance Brokers & Consultants','Alera Group','Higginbotham','IMA','World Insurance Associates LLC','Highstreet Insurance Partners','Trucordia','Hilb Group','Leavitt Group','Cross Insurance','Insurance Office of America Inc.','ALKEME','CAC Group','Patriot Growth Insurance Services LLC','Relation Insurance Inc.','Keystone Agency Partners LLC','TWFG','Heffernan Insurance Brokers','The Liberty Company Insurance Brokers','Inszone Insurance','INSURICA Insurance Services LLC','Hylant','Sunstar Insurance Group','Unison Risk Advisors','TrueNorth','AIS Insurance*','Shepherd Insurance','Towne Insurance**','Premier Group Insurance Inc.','Lawley Insurance','Oakbridge Insurance Agency LLC','OneDigital','Sterling Seacrest Pritchard','Marshall + Sterling Enterprises Inc.','Robertson Ryan Insurance','Houchens Insurance Group','Starkweather & Shepley Insurance Brokerage Inc.','Bowen, Miclette & Britt Insurance Agency LLC','Turner Surety & Insurance Brokerage','Atlas Insurance Brokers LLC','Signers National LLC','King Risk Partners','Superior Insurance Partners','Home Services Insurance','Vantage Insurance Partners','The Mahoney Group','NavSav Insurance','Reliance Partners','Crest Insurance Group','Rich & Cartmill Inc.','Charles L. Crane Agency','Christensen Group Inc.','Moreton & Company','Huntington Insurance**','Ansay & Associates LLC','TRICOR Insurance','R&R Insurance Services Inc.','Swingle Collins & Associates Inc.','OneGroup NY Inc.**','Hotchkiss Insurance','Frost Insurance Agency**','JMG','Buckner Company','Paramount Exclusive Insurance Services Inc.','James G Parker Insurance Associates','Sihle Insurance Group Inc.','Commercial Insurance Associates','Atlas Insurance Agency','Kapnick Insurance Group','Tompkins Insurance Agencies Inc.**','Associated Insurance Management LLC','The Plastridge Agency Inc.','OVD Insurance','The MJ Companies','BancFirst Insurance Services Inc.**','Ross & Yerger Insurance','The Daniel and Henry Company','Moody Insurance Agency Inc.','Rate Insurance LLC','Kaplansky Insurance','Watkins Insurance Group','CCIG','Haas & Wilkerson Insurance','C3 Risk & Insurance','Hausmann Group','TIS Insurance Services Inc.','Snellings Walters Insurance Agency','Mackoul Risk Solutions LLC.','Energy Insurance Agency','Florida One Insurance Agency','Dean & Draper Insurance Agency LP']::text[],
    ARRAY[3430361887,2854779000,2835000000,2374880000,1931090000,1826932000,1547352549,1262682994,1061048000,878358000,734000000,608778000,604325457,588000000,576719632,564669705,432915085,393521824,307000000,294768870,265000000,260042750,259029000,258960000,258309000,202442000,191693512,190000000,177320191,173640680,138321119,132000000,128765000,115626295,109400000,102981223,99459606,98185000,97599206,95075734,94600000,92252758,89277128,85911305,84469840,84074913,73993565,68981800,66887908,65936742,64572483,61526628,60000000,58000000,57206294,56125487,53306695,52644418,50370380,50197169,50002093,49428000,48593000,47181226,46750667,44674000,43180035,41940152,41400000,41093496,38390000,38119516,35625000,35386000,34459092,33719976,32437919,32148881,31263025,30560308,29446947,29261614,29241496,28015383,26645203,26296000,24525689,24501897,24442239,23540711,23316226,23236817,22258601,22175000,20528753,19968770,19364928,19321930,18534322,17957554]::numeric[],
    ARRAY[1643165385,1954941000,450500000,1627794000,1014594000,382668000,1301676819,39249331640,232058000,370174000,840000000,299721000,216939899,56000000,NULL,298775550,162474915,111291208,36000000,35863457,50000000,33489200,301018250,53040000,88540000,1318000,14405907,35000000,22654098,24938564,66734119,33000000,6935000,22203674,NULL,12541877,18649418,NULL,40917176,18464238,1205400000,24619868,49763312,5970091,27759637,7019782,13093748,166800,3915576,NULL,1366135,6114783,NULL,13000000,10419535,1015562,NULL,9433591,2469452,4751269,17633143,20292000,28455000,7161298,8272178,12839000,3164752,8722727,6000000,21410496,859770,5225274,550000,8165000,1003574,6819,10754310,100623,8503916,NULL,1979574,7199092,38600175,5103516,21322134,5586000,8803420,69328,1999734,5275967,3057608,NULL,5241050,8140000,5881033,5691100,900149,4126814,134322,2433486]::numeric[],
    ARRAY['Irvine','Chicago','Grand Rapids','Kansas City','Orlando','Columbus','Valhalla','Boston','Tampa','San Francisco','Deerfield','Fort Worth','Denver','Iselin','16','Lindon','Richmond','Cedar City','Bangor','Longwood','Ladera Ranch','Birmingham','Fort Washington','Chicago','Mechanicsburg','The Woodlands','Walnut Creek','Gainesville','Anaheim','Oklahoma City','Toledo','Memphis','Cleveland','Cedar Rapids','36','Carmel','Norfolk','39','Buffalo','LaGrange','Atlanta','Atlanta','Poughkeepsie','Milwaukee','Bowling Green','East Providence','Houston','Saddle Brook','Rochester','51','Gainesville','Chicago','54','New York','Chandler','Beaumont','58','Tucson','Tulsa','St. Louis','Eden Prairie','Salt Lake City','Columbus','Port Washington','Lancaster','Waukesha','Dallas','Syracuse','Carrollton','San Antonio','Norwalk','Salt Lake City','Encino','Fresno','Altamonte Springs','Brentwood','Honolulu','Adrian','Batavia','81','Delray Beach','Grand Rapids','Carmel','Oklahoma City','Jackson','St. Louis','Denver','Schaumburg','Needham','Austin','Englewood','93','San Diego','Madison','Knoxville','Atlanta','Long Beach','Lexington','Miami Lakes','Houston']::text[],
    ARRAY['California','Illinois','Michigan','Missouri','Florida','Ohio','New York','Massachusetts','Florida','California','Illinois','Texas','Colorado','New Jersey',NULL,'Utah','Virginia','Utah','Maine','Florida','California','Alabama','Pennsylvania','Illinois','Pennsylvania','Texas','California','Florida','California','Oklahoma','Ohio','Tennessee','Ohio','Iowa',NULL,'Indiana','Virginia',NULL,'New York','Georgia','Georgia','Georgia','New York','Wisconsin','Kentucky','Rhode Island','Texas','New Jersey','Minnesota',NULL,'Florida','Illinois',NULL,'New York','Arizona','Texas',NULL,'Arizona','Oklahoma','Missouri','Minnesota','Utah','Ohio','Wisconsin','Wisconsin','Wisconsin','Texas','New York','Texas','Texas','Connecticut','Utah','California','California','Florida','Tennessee','Hawaii','Michigan','New York',NULL,'Florida','Michigan','Indiana','Oklahoma','Mississippi','Missouri','Colorado','Illinois','Massachusetts','Texas','Colorado',NULL,'California','Wisconsin','Tennessee','Georgia','New York','Kentucky','Florida','Texas']::text[]
  ) AS u(rank, name, pc, other, city, state)
  RETURNING 1
),
members_b AS (
  INSERT INTO public.top_agency_members (top_agency_list_id, agency_name, region)
  SELECT (SELECT id FROM list_b), u.name, u.region
  FROM UNNEST(
    ARRAY['Woodruff Sawyer','Alliant Insurance Services – regional California retail operations (mid‑market)','Heffernan Insurance Brokers – California regional offices','Panorama Insurance Associates Inc.','Oakwood Insurance Agency (CA commercial retail)','Andreini & Company','InterWest Insurance Services','Bolton & Company (now MMA/others but still regional commercial presence)','HUB International Northwest – regional middle‑market focus','PayneWest Insurance – Pacific Northwest and Mountain region offices','Atlas Insurance Brokers – Western region offices (AZ, etc.)','The Buckner Company – Western states','Leavitt Group – California and Pacific regional agencies','Acrisure – various California retail brands (e.g., Tolman & Wiker)','Patriot Growth – West region agencies','World Insurance Associates – West region commercial offices','Andreini & Company – West Coast marine/transportation commercial','Heffernan Insurance Brokers – Oregon/Washington branches','PayneWest – Montana, Idaho, Washington commercial offices','Higginbotham – Texas and surrounding states commercial retail','INSURICA – Oklahoma, Texas, New Mexico regional offices','SWBC Insurance Services – Texas and Southwest commercial','Ross & Yerger Insurance – Mississippi and surrounding Southeast/Southwest reach','Rich & Cartmill – Oklahoma/Texas region','Frost Insurance Agency – Texas and regional commercial','Roach Howard Smith & Barton (now under AssuredPartners, still a TX commercial brand)','TWFG Insurance (where retail commercial)','Atlas Insurance Brokers – Arizona offices','PayneWest – regional operations overlapping Mountain/Southwest','Leavitt Group – multiple Southwest regional agencies','World Insurance Associates – Texas and Gulf region retail offices','Relation Insurance Services – Southwest regional offices','The IMA Financial Group – Denver and Southwest regional offices','INSURICA Insurance Management Network – Texas/Oklahoma regional agencies','Cross Insurance – New England regional commercial agency','OneGroup – New York and Northeast regional commercial agency','Rate Insurance – New York‑based independent commercial/personal broker','Haylor, Freyer & Coon – New York–based commercial broker','World Insurance Associates – Mid‑Atlantic and Northeast offices','Relation Insurance Services – Mid‑Atlantic/East Coast offices','Alera Group – regional agencies across East Coast','PayneWest’s parent MMA East region agencies','Alliant’s East Coast regional retail branches','Brown & Brown of New York','Brown & Brown of the Carolinas','Brown & Brown of Virginia','AssuredPartners East regional retail agencies','Patriot Growth – Mid‑Atlantic and Southeast agencies','Risk Strategies regional commercial offices on East Coast','USI Northeast retail offices','NFP P&C East region offices','R&R Insurance Services Inc. – Wisconsin/Midwest','Rich & Cartmill – Missouri/Kansas region','Charles L. Crane Agency Co. – St. Louis/Midwest commercial broker','Ross & Yerger – overlapping South and Midwest commercial','Atlas Insurance Brokers – Minnesota, Iowa, North Dakota, South Dakota','Chicagoland SIA – Illinois/Midwest agency network/cluster with commercial retail','John O. Bronson Co. (legacy regional commercial broker)','OneGroup – some Midwest presence via acquisitions','World Insurance Associates – Midwest regional offices','Relation Insurance Services – Midwest commercial offices','Leavitt Group – Midwest regional agencies','Brown & Brown of Michigan','Brown & Brown of Ohio','Brown & Brown of Indiana','USI Midwest regional offices','HUB International Midwest','Acrisure – Midwest regional retail brands','PayneWest – overlapping Mountain/Midwest territories','PayneWest Insurance – Montana, Idaho, Wyoming commercial','IMA Financial Group – Colorado, Kansas, surrounding Mountain region','The Buckner Company – Utah and Mountain states','Leavitt Group – Utah, Colorado, Nevada mountain‑region agencies','HUB International Mountain States offices','Brown & Brown of Colorado','Brown & Brown of Nevada','World Insurance Associates – selected Mountain regional branches','Relation Insurance Services – Mountain region offices','USI Mountain regional offices','Ross & Yerger Insurance – Mississippi and Gulf states','World Insurance Associates – Southeast offices','Risk Strategies – Southeast regional retail','Alera Group – Southeast regional agencies','Relation Insurance Services Southeast','Patriot Growth – Southeast agencies','Brown & Brown of Florida','Brown & Brown of Georgia','Brown & Brown of the Carolinas','HUB International Southeast','USI Southeast','Atlas Insurance Agency (Honolulu, Hawaii commercial and personal lines)','Finance Insurance Ltd. (Hawaii regional commercial agency)','King & Neel (Hawaii commercial broker)','HUB International – Alaska regional office','Alaska USA Insurance Brokers (commercial and personal)','USI Insurance Services – Washington DC Metro','HUB International – Mid‑Atlantic/DC office','Brown & Brown – Mid‑Atlantic/DC office','Risk Strategies – DC/Metro commercial practice','Alera Group – DC/Baltimore regional agencies','World Insurance Associates – DC/Mid‑Atlantic agencies']::text[],
    ARRAY['Californian/West Coast & PNW regional commercial agencies','Californian/West Coast & PNW regional commercial agencies','Californian/West Coast & PNW regional commercial agencies','Californian/West Coast & PNW regional commercial agencies','Californian/West Coast & PNW regional commercial agencies','Californian/West Coast & PNW regional commercial agencies','Californian/West Coast & PNW regional commercial agencies','Californian/West Coast & PNW regional commercial agencies','Californian/West Coast & PNW regional commercial agencies','Californian/West Coast & PNW regional commercial agencies','Californian/West Coast & PNW regional commercial agencies','Californian/West Coast & PNW regional commercial agencies','Californian/West Coast & PNW regional commercial agencies','Californian/West Coast & PNW regional commercial agencies','Californian/West Coast & PNW regional commercial agencies','Californian/West Coast & PNW regional commercial agencies','Californian/West Coast & PNW regional commercial agencies','Californian/West Coast & PNW regional commercial agencies','Californian/West Coast & PNW regional commercial agencies','Southwest (including TX, OK, NM, AZ)','Southwest (including TX, OK, NM, AZ)','Southwest (including TX, OK, NM, AZ)','Southwest (including TX, OK, NM, AZ)','Southwest (including TX, OK, NM, AZ)','Southwest (including TX, OK, NM, AZ)','Southwest (including TX, OK, NM, AZ)','Southwest (including TX, OK, NM, AZ)','Southwest (including TX, OK, NM, AZ)','Southwest (including TX, OK, NM, AZ)','Southwest (including TX, OK, NM, AZ)','Southwest (including TX, OK, NM, AZ)','Southwest (including TX, OK, NM, AZ)','Southwest (including TX, OK, NM, AZ)','Southwest (including TX, OK, NM, AZ)','East Coast & Atlantic States (Northeast/Mid‑Atlantic/SE coast)','East Coast & Atlantic States (Northeast/Mid‑Atlantic/SE coast)','East Coast & Atlantic States (Northeast/Mid‑Atlantic/SE coast)','East Coast & Atlantic States (Northeast/Mid‑Atlantic/SE coast)','East Coast & Atlantic States (Northeast/Mid‑Atlantic/SE coast)','East Coast & Atlantic States (Northeast/Mid‑Atlantic/SE coast)','East Coast & Atlantic States (Northeast/Mid‑Atlantic/SE coast)','East Coast & Atlantic States (Northeast/Mid‑Atlantic/SE coast)','East Coast & Atlantic States (Northeast/Mid‑Atlantic/SE coast)','East Coast & Atlantic States (Northeast/Mid‑Atlantic/SE coast)','East Coast & Atlantic States (Northeast/Mid‑Atlantic/SE coast)','East Coast & Atlantic States (Northeast/Mid‑Atlantic/SE coast)','East Coast & Atlantic States (Northeast/Mid‑Atlantic/SE coast)','East Coast & Atlantic States (Northeast/Mid‑Atlantic/SE coast)','East Coast & Atlantic States (Northeast/Mid‑Atlantic/SE coast)','East Coast & Atlantic States (Northeast/Mid‑Atlantic/SE coast)','East Coast & Atlantic States (Northeast/Mid‑Atlantic/SE coast)','Midwest','Midwest','Midwest','Midwest','Midwest','Midwest','Midwest','Midwest','Midwest','Midwest','Midwest','Midwest','Midwest','Midwest','Midwest','Midwest','Midwest','Midwest','Mountain States','Mountain States','Mountain States','Mountain States','Mountain States','Mountain States','Mountain States','Mountain States','Mountain States','Mountain States','Southeast/Atlantic (beyond Top 100 national names)','Southeast/Atlantic (beyond Top 100 national names)','Southeast/Atlantic (beyond Top 100 national names)','Southeast/Atlantic (beyond Top 100 national names)','Southeast/Atlantic (beyond Top 100 national names)','Southeast/Atlantic (beyond Top 100 national names)','Southeast/Atlantic (beyond Top 100 national names)','Southeast/Atlantic (beyond Top 100 national names)','Southeast/Atlantic (beyond Top 100 national names)','Southeast/Atlantic (beyond Top 100 national names)','Southeast/Atlantic (beyond Top 100 national names)','Alaska, Hawaii, DC (commercial P/C retail)','Alaska, Hawaii, DC (commercial P/C retail)','Alaska, Hawaii, DC (commercial P/C retail)','Alaska, Hawaii, DC (commercial P/C retail)','Alaska, Hawaii, DC (commercial P/C retail)','DC‑area regional offices of:','DC‑area regional offices of:','DC‑area regional offices of:','DC‑area regional offices of:','DC‑area regional offices of:','DC‑area regional offices of:']::text[]
  ) AS u(name, region)
  RETURNING 1
)
SELECT
  (SELECT count(*) FROM members_a) AS inserted_top100,
  (SELECT count(*) FROM members_b) AS inserted_regional;